CLIENT_ADDR_IPV4: 172.16.166.151
TO_SERVER_PORT: 9000
MANAGER_PORT: 5000
MANAGER_ADDR_IPV4: '172.16.166.151'
TO_MANAGER_PORT: 6000
TMP_DIR: './ddr-download/client/tmp/'
PROXIES:
  HTTP:
  HTTPS:
TARGET_DIR: './ddr-download/client/target/'
